src/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import UserLoginView, user_reactivation_view
from .views import UserLogoutView
from .views import UserProfileUpdateView
from .views import UserRegisterView
from .views import user_activate
from .views import user_profile_view

app_name = 'accounts'

urlpatterns = [
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('register/done/', TemplateView.as_view(template_name='accounts/user_register_done.html'),
         name='register_done'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', user_profile_view, name='profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('reactivate/', user_reactivation_view, name='reactivate'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task.views import get_status, home, run_task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
    path('home/', home, name='task_home'),
    path('tasks/<task_id>/', get_status, name='get_status'),
    path('tasks/', run_task, name='run_task'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from .views import ExamDetailView
from .views import ExamListView
from .views import ExamResultCreateView
from .views import ExamResultDeleteView
from .views import ExamResultDetailView
from .views import ExamResultQuestionView
from .views import ExamResultUpdateView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    # path('<uuid:uuid>/result/<uuid:res_uuid>/question/<int:order_num>/', ExamResultQuestionView.as_view(),
    #      name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/next/', ExamResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
]

src/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top" style="background-color: #e3f2fd">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'quiz:list' %}">Exam list</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'task_home' %}">Tasks</a>
                </li>
            </ul>
            {% if request.path %}

            {% endif %}
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

src/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

src/templates/includes/paginator.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1"><i class="bi bi-chevron-bar-left"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="bi bi-chevron-left"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-bar-left"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-left"></i></a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
                <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% elif page_obj.number < 3 and page_num < 6 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% elif page_obj.number > page_obj.paginator.num_pages|add:-2 and page_num > page_obj.paginator.num_pages|add:-5 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="bi bi-chevron-right"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><i class="bi bi-chevron-bar-right"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-right"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-bar-right"></i></a></li>
        {% endif %}
    </ul>
</nav>