src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task.views import get_status, home, run_task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
    path('home/', home, name='task_home'),
    path('tasks/<task_id>/', get_status, name='get_status'),
    path('tasks/', run_task, name='run_task'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from .views import ExamDetailView
from .views import ExamListView
from .views import ExamResultCreateView
from .views import ExamResultDeleteView
from .views import ExamResultDetailView
from .views import ExamResultQuestionView
from .views import ExamResultUpdateView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    # path('<uuid:uuid>/result/<uuid:res_uuid>/question/<int:order_num>/', ExamResultQuestionView.as_view(),
    #      name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/next/', ExamResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
]

src/quiz/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models


class BaseModel(models.Model):
    create_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 100

    class LEVEL(models.IntegerChoices):
        BASIC = 0, 'Basic',
        MIDDLE = 1, 'Middle',
        ADVANCED = 2, 'Advanced',

    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def __str__(self):
        return self.title

    def question_count(self):
        return self.questions.count()

    class Meta:
        db_table = 'exam'
        verbose_name = 'Exam'
        verbose_name_plural = 'Exams'


class Question(BaseModel):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='questions')
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=1024)
    image = models.ImageField(upload_to='questions/', null=True, blank=True)

    def __str__(self):
        return self.text

    class Meta:
        db_table = 'question'
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class Choice(BaseModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    class Meta:
        db_table = 'choice'
        verbose_name = 'Choice'
        verbose_name_plural = 'Choices'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, 'New',
        FINISHED = 1, 'Finished',

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='results')
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='results')
    state = models.PositiveSmallIntegerField(choices=STATE.choices, default=STATE.NEW)
    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(default=0)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = 'result'
        verbose_name = 'Result'
        verbose_name_plural = 'Results'

    def update_result(self, order_number, question, select_choices):
        correct_choice = [choice.is_correct for choice in question.choices.all()]
        correct_answer = True
        for zip_group in zip(select_choices, correct_choice):
            correct_answer = correct_answer and (zip_group[0] == zip_group[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number

        if order_number == question.exam.questions.count():
            self.state = self.STATE.FINISHED

        self.save()

    def calculate_points(self):
        # calculated_points = self.num_correct_answers - self.num_incorrect_answers
        # return calculated_points if calculated_points >= 0 else 0

        return max(0, self.num_correct_answers-self.num_incorrect_answers)

src/quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Choice


class QuestionInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError(
                f'Question count must be range '
                f'from {self.instance.QUESTION_MIN_LIMIT} '
                f'to {self.instance.QUESTION_MAX_LIMIT} inclusive'
            )

        index = 1
        for form in self.forms:
            if form.cleaned_data['order_num'] != index:
                raise ValidationError(
                    f'Question order number must be in range '
                    f'from 1 to {self.instance.QUESTION_MAX_LIMIT} and '
                    f'greater than previous by 1'
                )
            elif self.instance.QUESTION_MAX_LIMIT < form.cleaned_data['order_num']:
                raise ValidationError(
                    f'Question order number must be less than {self.instance.QUESTION_MAX_LIMIT} inclusive'
                )
            index += 1


class ChoiceInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        num_correct_answers = sum(form.cleaned_data['is_correct'] for form in self.forms)

        if num_correct_answers == 0:
            raise ValidationError('Need to choose one option minimum')

        if num_correct_answers == len(self.forms):
            raise ValidationError('It is not allowed to select all options')


class ChoiceForm(forms.ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Choice
        fields = ('text',)


ChoicesFormSet = forms.modelformset_factory(
    model=Choice,
    form=ChoiceForm,
    extra=0
)

src/quiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic.list import MultipleObjectMixin

from .forms import ChoicesFormSet
from .models import Exam
from .models import Question
from .models import Result


class ExamListView(LoginRequiredMixin, ListView):
    model = Exam
    template_name = 'exam/list.html'
    context_object_name = 'exams'


class ExamDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Exam
    template_name = 'exam/details.html'
    context_object_name = 'exam'
    pk_url_kwarg = 'uuid'
    paginate_by = 3

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)

        return context

    def get_queryset(self):
        return Result.objects.filter(
            exam=self.get_object(),
            user=self.request.user
        ).order_by('state', '-create_timestamp')


class ExamResultCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result = Result.objects.create(
            user=request.user,
            exam=Exam.objects.get(uuid=uuid),
            state=Result.STATE.NEW
        )

        result.save()

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': result.uuid,
                    # 'order_num': 1
                }
            )
        )


class ExamResultQuestionView(LoginRequiredMixin, UpdateView):
    def get_params(self, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        # order_num = kwargs.get('order_num')
        order_num = Result.objects.filter(
            uuid=res_uuid, user=self.request.user
        ).values('current_order_number').first()['current_order_number'] + 1

        return uuid, res_uuid, order_num

    def get_question(self, uuid, order_num):
        return Question.objects.get(
            exam__uuid=uuid,
            order_num=order_num,
        )

    def get(self, request, *args, **kwargs):
        uuid, res_uuid, order_num = self.get_params(**kwargs)
        question = self.get_question(uuid, order_num)

        choices = ChoicesFormSet(queryset=question.choices.all())

        return render(request, 'exam/question.html', context={'question': question, 'choices': choices})

    def post(self, request, *args, **kwargs):
        uuid, res_uuid, order_num = self.get_params(**kwargs)
        question = self.get_question(uuid, order_num)

        choices = ChoicesFormSet(data=request.POST)
        selected_choices = ['is_selected' in form.changed_data for form in choices.forms]

        if not any(selected_choices) or all(selected_choices):
            messages.error(self.request, 'You need to select at least one, but not all answers.')
        else:
            result = Result.objects.get(uuid=res_uuid)
            result.update_result(order_num, question, selected_choices)

            if result.state == Result.STATE.FINISHED:
                return HttpResponseRedirect(
                    reverse(
                        'quiz:result_details',
                        kwargs={
                            'uuid': uuid,
                            'res_uuid': result.uuid
                        }
                    )
                )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': res_uuid,
                    # 'order_num': order_num + 1
                }
            )
        )


class ExamResultDetailView(LoginRequiredMixin, DetailView):
    model = Result
    template_name = 'result/details.html'
    context_object_name = 'result'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=uuid)


class ExamResultUpdateView(LoginRequiredMixin, UpdateView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        # user = request.user

        # result = Result.objects.get(
        #     user=user,
        #     uuid=res_uuid,
        #     exam__uuid=uuid,
        # )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': res_uuid,
                    # 'order_num': result.current_order_number + 1
                }
            )
        )


class ExamResultDeleteView(LoginRequiredMixin, DeleteView):
    model = Result
    template_name = 'result/delete.html'
    context_object_name = 'result'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=uuid)

    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        result = Result.objects.get(
            uuid=res_uuid,
            user=request.user,
            exam=Exam.objects.get(uuid=uuid),
            state=Result.STATE.NEW
        )

        result.delete()

        return HttpResponseRedirect(
            reverse(
                'quiz:details',
                kwargs={
                    'uuid': uuid,
                }
            )
        )

src/quiz/templates/exam/details.html
{% extends 'base.html' %}

{% block title %}
    Details of exam
{% endblock %}

{% block header %}
    {{ exam.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Description</td>
                            <td>{{ exam.description }}</td>
                        </tr>
                        <tr>
                            <td>Questions count</td>
                            <td>{{ exam.questions.count }}</td>
                        </tr>
                        <tr>
                            <td>Runs count</td>
                            <td>{{ exam.results.count }}</td>
                        </tr>
                        {% with best_res=exam.results.all|dictsort:"num_correct_answers"|last %}
                            <tr>
                                <td>Best result</td>
                                <td>
                                    {% if best_res %}
                                        {{ best_res.num_correct_answers }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Best user</td>
                                <td>
                                    {% if best_res %}
                                        {{ best_res.user }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                            </tr>
                        {% endwith %}
                        {% with last_start=exam.results.all|dictsort:"update_timestamp"|last %}
                            <tr>
                                <td>Last run</td>
                                <td>
                                    {% if last_start %}
                                        {{ last_start.update_timestamp|date:'d-M-Y H:i' }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                </td>
                            </tr>
                        {% endwith %}
                    </tbody>
              </table>
            </div>
        </div>
        <div class="row">
            <form method="post" class="d-flex justify-content-center mt-1 mb-2"
                  action="{% url 'quiz:result_create' exam.uuid %}">
                {% csrf_token %}
                <input class="btn btn-outline-success m-2" type="submit" value="START">
                <a class="btn btn-outline-primary m-2" href="{% url 'quiz:list' %}">Back to exams list</a>
            </form>
        </div>
        {% if object_list %}
            <table class="table table-striped table-hover">
                <tr>
                    <th></th>
                    <th>Start date</th>
                    <th>Points</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                {% for result in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ result.create_timestamp|date:'d-M-Y H:i' }}</td>
                    <td>{{ result.calculate_points }}</td>
                    <td>{{ result.get_state_display }}</td>
                    <td>
                        {% if result.state == result.STATE.NEW %}
                            <a class="btn btn-outline-warning" href="{% url 'quiz:result_update' exam.uuid result.uuid %}">
                                Continue
                            </a>
                            <a class="btn btn-outline-danger" href="{% url 'quiz:result_delete' exam.uuid result.uuid %}">
                                Remove
                            </a>
                        {% else %}
                            <a class="btn btn-outline-success" href="{% url 'quiz:result_details' exam.uuid result.uuid %}">
                                View
                            </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% endif %}
        {% if is_paginated %}
            <div class="row">
                {% include 'includes/paginator.html' %}
            </div>
        {% endif %}
    </div>
{% endblock %}

src/quiz/templates/exam/list.html
{% extends 'base.html' %}

{% block title %}
    Exam list
{% endblock %}

{% block header %}
    Exam list
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quiz:details' uuid=exam.uuid %}">Details</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no tests yet!</p>
    {% endif %}
{% endblock %}

src/quiz/templates/exam/question.html
{% extends 'base.html' %}

{% load calculate %}

{% block title %}
    Test description
{% endblock %}

{% block header %}
    {{ question.order_num }}) {{ question.text }}
    {% expression '(%1 - 1) * 100 // %2' question.order_num question.exam.question_count as level %}
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
             role="progressbar"
             aria-label="Animated striped example"
             aria-valuenow="{{ level }}"
             style="width: {{ level }}%"
             aria-valuemin="0"
             aria-valuemax="100">{{ level }}%
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% include 'includes/messages.html' %}
        <form method="post" autocomplete="off">
            {% csrf_token %}
            {{ choices.management_form }}
            {% for form in choices %}
                <div class="mt-1">
                    {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}">
                    {{ form.text.value }}
                </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-success mt-5">Next ></button>
        </form>
    </div>
{% endblock %}